name: Deploy Debug

on:
  workflow_dispatch: # Manual trigger only

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout debug branch
        uses: actions/checkout@v2
        with:
          ref: debug # Force checkout of debug regardless of trigger branch

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.17.1'

      - name: Install dependencies
        run: yarn

      - name: Build the React app
        run: yarn build

      - name: Deploy to server via SFTP
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          key: ${{ secrets.SFTP_KEY }}
          port: 22
          source: 'build/*'
          target: '/var/www/html/accreditation-debug/'
          strip_components: 1
